### ISSUE TITLE
Make the title and message of the AlertDialog editable.

### ISSUE THREAD

**Issue by mkpazon** [stkent/bugshaker-android#112]
My use-case is I have a "Report a Bug" button, and when the user taps it BugShaker says "Shake detected!" which is not the case. It would be nice if we can make the title and message editable. Probably another method like show or a simple overload of hearShake() to accept title and message parameters.

**Comment by stkent** [comment]
I think, similarly to #94, I'm going to decline this feature request for now since it's not core to the functionality of Bug_Shaker_. It should be fairly simple to fork the library and edit the [relevant constants](https://github.com/stkent/bugshaker-android/blob/72ab89c553761aab13e34377517043126f8f584d/bugshaker/src/main/java/com/github/stkent/bugshaker/flow/dialog/DialogProvider.java#L26-L27) if that's absolutely a requirement for you at this time.

(I've been thinking about whether it would be easy to abstract the bug report trigger mechanism; if so, and I choose to follow that path, I'll revisit this issue at that time :))
